# Generated by Django 5.1.4 on 2024-12-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Setting',
        ),
    ]
